services:
  www-pybots:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: www-pybots
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
